[package]
name = "synthetic_data"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tch = { version = "0.10", default-features = false }
rand = "0.8"
rand_distr = "0.4"

[profile.release]
rpath = true
